### PR TITLE
Blog post on PMG's as-enacted PDF acts

### PR DESCRIPTION
**Pull request by longhotsummer**
@nefiger @xybrnet please take a quick look when you have a sec.

### CODE REVIEW

**Comment by nefiger** [comment]
Looks pretty good. I'd love to understand the process a bit more (relationship of acts to bills and what as-enacted actually means)

**Comment by xybrnet** [comment]
Yip, looks good to me too. And I agree about the definitions.

**Comment by longhotsummer** [comment]
@nefiger @xybrnet  updated

**Comment by xybrnet** [comment]
Looks good to me.

**Comment by longhotsummer** [comment]
Ok merging.

**Pull request merged**
