### PR TITLE
Use Code4SA stylesheets, twitter sharing, nicer blog layouts

### PR DESCRIPTION
**Pull request by longhotsummer**
- use our Code4SA stylesheet to make our site look a tad better, and give us some experience using the stylesheet.
- add author metadata for all blog posts to let us have a nicer blog post page.
- add FB and Twitter sharing buttons for blog posts
- remove some old pages
- update fontawesome

### CODE REVIEW

**Comment by longhotsummer** [comment]
This replaces #40

**Comment by adieyal** [comment]
I'm not convinced by the blue background in the banner
What is that weird box on the top right next to @code4sa?
I'm not a fan of the blog format - there a lots of cool looking blogs out there. Can't we borrow from them?

**Comment by longhotsummer** [comment]
The weird box was the old twitter icon -- I've removed it.

Do you have any examples of blog layouts you like?

How about a large background image -- maybe of a data quest -- in the main header?

**Comment by longhotsummer** [comment]
Merging. Hooray for iteration.

**Pull request merged**
